productions = {
    "Program": [["Declaration-list", "$"]],
    "Declaration-list": [["Declaration", "Declaration-list"], ["epsilon"]],
    "Declaration": [["Declaration-initial", "Declaration-prime"]],
    "Declaration-initial": [["Type-specifier", "ID", "#gp_id"]],
    "Declaration-prime": [["Fun-declaration-prime"], ["Var-declaration-prime"]],
    "Var-declaration-prime": [[";", "#add_id"], ["[", "NUM", "#gp_id", "]", ";", "#add_array"]],
    "Fun-declaration-prime": [["#add_fun", "(", "Params", ")", "#set_nopar", "Compound-stmt"]],
    "Type-specifier": [["int", "#push_int"], ["void", "#push_void"]],
    "Params": [
        ["int", "#push_int", "ID", "#gp_id", "#inc_par", "Param-prime", "Param-list"],
        ["void"],
    ],
    "Param-list": [[",", "Param", "Param-list"], ["epsilon"]],
    "Param": [["Declaration-initial", "Param-prime", "#inc_par"]],
    "Param-prime": [["[", "]", "#add_pararr"], ["epsilon", "#add_id"]],
    "Compound-stmt": [["{", "Declaration-list", "#set_fun_pointer", "Statement-list", "}"]],
    "Statement-list": [["Statement", "Statement-list"], ["epsilon"]],
    "Statement": [
        ["Expression-stmt"],
        ["Compound-stmt"],
        ["Selection-stmt"],
        ["Iteration-stmt"],
        ["Return-stmt"],
    ],
    "Expression-stmt": [["Expression", ";", "#pop"], ["break", ";", "#set_break"], [";"]],
    "Selection-stmt": [
        ["if", "(", "Expression", ")", "#save", "Statement", "#jpf_if", "Else-stmt", "#jp"]
    ],
    "Else-stmt": [["endif"], ["else", "Statement", "endif"]],
    "Iteration-stmt": [["repeat", "#save_r", "Statement", "until", "(", "Expression", ")", "#jpf_repeat"]],
    "Return-stmt": [["return", "Return-stmt-prime"]],
    "Return-stmt-prime": [[";", "#return_jp"], ["Expression", ";", "#return_sjp"]],
    "Expression": [["Simple-expression-zegond"], ["ID", "#get_id", "B"]],
    "B": [["=", "Expression", "#assign"], ["[", "Expression", "]", "#get_array_item", "H"], ["Simple-expression-prime"]],
    "H": [["=", "Expression", "#assign"], ["G", "D", "C"]],
    "Simple-expression-zegond": [["Additive-expression-zegond", "C"]],
    "Simple-expression-prime": [["Additive-expression-prime", "C"]],
    "C": [["Relop", "Additive-expression"], ["epsilon"]],
    "Relop": [["<", "#push_LT"], ["==", "#push_EQ"]],
    "Additive-expression": [["Term", "D"]],
    "Additive-expression-prime": [["Term-prime", "D"]],
    "Additive-expression-zegond": [["Term-zegond", "D"]],
    "D": [["Addop", "Term", "D"], ["epsilon"]],
    "Addop": [["+", "#push_ADD"], ["-", "#push_SUB"]],
    "Term": [["Factor", "G"]],
    "Term-prime": [["Factor-prime", "G"]],
    "Term-zegond": [["Factor-zegond", "G"]],
    "G": [["*", "#push_MULT", "Factor", "G"], ["epsilon"]],
    "Factor": [["(", "Expression", ")"], ["ID", "#get_id", "Var-call-prime"], ["NUM", "#get_num"]],
    "Var-call-prime": [["(", "#reset_no", "Args", ")", "#call_fun"], ["Var-prime"]],
    "Var-prime": [["[", "Expression", "]", "#get_array_item"], ["epsilon"]],
    "Factor-prime": [["(", "#reset_no", "Args", ")", "#call_fun"], ["epsilon"]],
    "Factor-zegond": [["(", "Expression", ")"], ["NUM", "#get_num"]],
    "Args": [["Arg-list"], ["epsilon"]],
    "Arg-list": [["Expression", "#add_arg", "Arg-list-prime"]],
    "Arg-list-prime": [[",", "Expression", "#add_arg", "Arg-list-prime"], ["epsilon"]],
}
